# Generated by Django 4.2.4 on 2023-09-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_userinfo_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='bio',
            field=models.CharField(default='', max_length=200),
        ),
    ]
