# Generated by Django 4.2.4 on 2023-09-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_info_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='bio',
            field=models.CharField(max_length=200),
        ),
    ]
